import { db } from "../src/lib/db"
import bcrypt from "bcryptjs"

async function main() {
  const existing = await db.user.count()
  if (existing > 0) {
    console.log(`Database already has ${existing} user(s). Skipping admin seed.`)
    return
  }
  const passwordHash = await bcrypt.hash("pass", 10)
  const admin = await db.user.create({
    data: {
      username: "admin",
      passwordHash,
      isAdmin: true,
      mustChangePassword: true,
      // keypair is generated by the admin in their own browser on first login / password change
    },
  })
  console.log(`Seeded admin account: id=${admin.id}`)
  console.log("Default admin login -> username: admin  password: pass")
  console.log("You will be forced to change this password on first login.")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
