import { NextResponse } from "next/server"
import { db } from "@/lib/db"
import { getSession, hashPassword } from "@/lib/auth"
import { broadcastUsersChanged } from "@/lib/socket-notify"

export async function GET() {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const users = await db.user.findMany({
    orderBy: { username: "asc" },
    select: {
      id: true,
      username: true,
      displayName: true,
      isAdmin: true,
      publicKey: true,
      mustChangePassword: true,
      createdAt: true,
    },
  })
  return NextResponse.json({ users, me: { id: session.id } })
}

export async function POST(req: Request) {
  const session = await getSession()
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  if (!session.isAdmin) {
    return NextResponse.json({ error: "Only the admin can create accounts" }, { status: 403 })
  }
  const body = await req.json().catch(() => ({}))
  const username = String(body.username || "").trim().toLowerCase()
  const tempPassword = String(body.tempPassword || "")
  if (!username || !tempPassword) {
    return NextResponse.json({ error: "Username and temporary password are required" }, { status: 400 })
  }
  const existing = await db.user.findUnique({ where: { username } })
  if (existing) {
    return NextResponse.json({ error: "Username already taken" }, { status: 409 })
  }
  const passwordHash = await hashPassword(tempPassword)
  const user = await db.user.create({
    data: {
      username,
      passwordHash,
      isAdmin: false,
      mustChangePassword: true,
      // keypair is generated by the new user in their own browser on first login
    },
  })
  await broadcastUsersChanged()
  return NextResponse.json({
    user: {
      id: user.id,
      username: user.username,
      isAdmin: user.isAdmin,
      mustChangePassword: user.mustChangePassword,
      createdAt: user.createdAt,
    },
  })
}
